name: Build and deploy Node.js project to Azure Function App - ProdTenableDCJFunction

on:
  push:
    branches:
      - main
    paths:
      - 'Tenable/TenableFunction/**' # Triggers the workflow on changes within this specific path
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Tenable/TenableFunction' # Path to your web app project within the repo
  NODE_VERSION: '18.x' # Node.js version to use
  FUNCTION_APP_NAME: 'ProdTenableDCJFunction' # Azure Function App name

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Resolve Project Dependencies Using Npm
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm install
          npm run build --if-present
          npm run test --if-present
        shell: pwsh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ${{ github.workspace }}/${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }} # Using the Azure Function App name from the environment variable
          slot-name: 'Production'
          package: '.' # Specifies to deploy the content of the downloaded artifact
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_92F8F14D0
