name: Build and deploy Node.js project to Azure Function App - ProdTenableDCJFunction

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Tenable' # Set this to the path to your Tenable project
  NODE_VERSION: '18.x' # Set this to the node version to use

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: pwsh
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} # Changed from pushd to cd for simplicity
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} # Specify the path to upload

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.fa.outputs.webapp-url }} # Ensure this output variable matches the step ID of your deployment step
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_58AA84B4C1184BEE8CCE2F73A6027684 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0831854EE39D401CA53F8490D3A81461 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0440FB38283F47C08880C068A548E3B2 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'ProdTenableDCJFunction'
          slot-name: 'Production'
          package: . # Since you're downloading the artifact to the runner's current directory
