name: Build and deploy Node.js project to Azure Function App - ProdTenableDCJFunction

on:
  push:
    branches:
      - main
    paths:
      - 'Tenable/**' # Monitor changes in the Tenable folder broadly
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'  # Node.js version to use
  FUNCTION_APP_NAME: ProdTenableDCJFunction  # Azure Function App name
  FUNCTION_APP_DIR: Tenable  # Parent directory containing the Node.js project
  FUNCTION_CODE_DIR: Tenable/TenableFunction  # Specific function directory to deploy

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies at Project Root
        run: |
          cd ${{ env.FUNCTION_APP_DIR }}
          npm install
        shell: pwsh

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # This secret needs to contain the Azure service principal JSON

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          slot-name: production
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: ${{ env.FUNCTION_CODE_DIR }}

      - name: List Deployment Output
        run: |
          Write-Output "Deployment to ${{ env.FUNCTION_APP_NAME }} completed successfully."
        shell: pwsh
