name: Build and deploy Node.js project to Azure Function App - ProdTenableDCJFunction

on:
  push:
    branches:
      - main
    paths:
      - 'Tenable/**' # Adjusted to monitor changes in the Tenable folder broadly
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'  # Set this to the node version to use
  FUNCTION_APP_NAME: ProdTenableDCJFunction  # Your Azure Function App name
  FUNCTION_APP_DIR: Tenable  # The parent directory
  FUNCTION_CODE_DIR: Tenable/TenableFunction  # The specific function directory

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies at Project Root
        run: |
          cd ${{ env.FUNCTION_APP_DIR }}
          npm install
        shell: pwsh

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          slot-name: production
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: ${{ env.FUNCTION_CODE_DIR }}  # Specifies the function code directory for deployment

      - name: List Deployment Output
        run: |
          Write-Output "Deployment to ${{ env.FUNCTION_APP_NAME }} completed successfully."
        shell: pwsh
