name: Build and deploy Node.js project to Azure Function App - ProdTenableDCJFunction

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: |
          cd Tenable/TenableFunction
          npm install

      - name: Build Project (if applicable)
        run: |
          cd Tenable/TenableFunction
          npm run build --if-present

      - name: Run Tests (if applicable)
        run: |
          cd Tenable/TenableFunction
          npm run test --if-present

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: Tenable/TenableFunction

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'ProdTenableDCJFunction'
          slot-name: 'Production'
          package: . # Assumes the working directory contains your function app
